name = "globe-news-frontend"
main = "app.py"
compatibility_date = "2024-01-01"

[build]
command = "pip install -r requirements.txt"

[env.production]
vars = { BACKEND_URL = "https://p01--backend-api--5pt6gkpwq49b.code.run" }
